import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Menu } from "../lib/components/menu";
import Footer from "../lib/components/footer/Footer";
import { Header }  from "../lib/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50 text-gray-800`}>
        <Header>
          <Menu />
        </Header>
        <main className="container mx-auto p-4" >
          {children}
        </main>
        <Footer />
        </body>
    </html>
  );
}
